### ISSUE TITLE
Creating your own environments

### ISSUE THREAD

**Issue by mehmetkiraz93** [robotology/gym-ignition#164]
Hello,

First of all I would like to say, this is a great contribution to RL community. Thank you so much for your work!

I would like to ask, if it is possible now to create and use our own environments with different URDF, SDF files?
P.S. I have never used Ignition Gazebo before. But Im having too much trouble in Gazebo right now for a reproducible environment. For this reason, I want to implement my model in Ignition Gazebo again.
Thank you so much in advance!

**Comment by diegoferigo** [comment]
Hi @mehmetkiraz93, the main point of gym-ignition is to provide all the necessary tooling to create robotic environments. You can specify a `.world` file for the scene, a `.sdf` or `.urdf` with the robot model, and design a `Task` containing the environment logic.

I published the last release a couple of days ago and it's already usable. However, documentation is still not complete. You can learn a lot from our [testing suite](https://github.com/robotology/gym-ignition/tree/master/tests/python).

There are few things to keep in mind:

- With the current implementation, the `Task` could access only the robot object it handles. Assuming a manipulation example, the `Task` will operate on a robotic arm, and it can read data from and send references to the arm. Though, right now it cannot access the state of other simulated models, like an object on a table. So far we used the framework only for locomotion, and we didn't suffer of this limitation.
- In order to overcome the previous limitation, we are in the middle of a refactoring #155. When it will be finalized, `Task`s will have access to the entire simulation state. This change will break the existing APIs, therefore if you develop a `Task` class with the current APIs, you will need to update it as soon as we release the next version. You can expect the new APIs to hit the nightly channel in one or two months.
