### ISSUE TITLE
Docker Demo not showing GUI

### ISSUE THREAD

**Issue by raffaello-camoriano** [robotology/gym-ignition#97]
Hi, I started having a look at the code and tried running the Docker demo from the readme out of the box without GPU on Ubuntu 18.04.

It generates the following text output:

[gym-ignition_demo_out.txt](https://github.com/robotology/gym-ignition/files/3816128/gym-ignition_demo_out.txt)

It also opens a Gazebo windows which remains black and closes after ~1s.

A non-exhaustive list of possibly related outputs I found in the verbose output are:
```

[...]

libGL error: No matching fbConfigs or visuals found

[...]

libGL error: failed to load driver: swrast

[...]

Aborted (core dumped)

[...]
```

Questions for @diegoferigo :
1) Is the rest of the execution running as it should from what you can see from the log?
2) How should the visuals look like? What could the problem be?

Thanks.

**Comment by diegoferigo** [comment]
Hi @raffaello-camoriano, I suspect that you are running the docker image from a computer that has an Nvidia GPU. In this configuration, the docker image must have the GPU support, otherwise OpenGL-based application would not work.

Installing the resources needed by this configuration goes out of the scope of the README and they have not been reported. Though, it's quite simple, just follow the [rocker](https://github.com/osrf/rocker) and [nvidia-docker](https://github.com/NVIDIA/nvidia-docker) installation instructions.

As an alternative, if you have prime and you can switch off your GPU, you can use the reported command line entry for Intel.
